name: Weiner Family Studios
favicon: null
layout_spectrum: 0.93278
typography_spectrum: 0.42074
title: Family is forever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fad0a5'
    - '#808080'
    - '#ff0000'
    - '#0000ff'
  brandStrength: 0.5
  lightness: 0.568130059633404
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
